# Generated by Django 5.1 on 2024-10-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_like_delete_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
